[[redirects]]
  from = "/api/*"
  to = "https://backend-wbd-project.onrender.com"
  status = 200

[[redirects]]
  from = "/user/*"
  to = "https://backend-wbd-project.onrender.com"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "https://backend-wbd-project.onrender.com"
  status = 200
  
[[redirects]]
  from = "/auth/*"
  to = "https://backend-wbd-project.onrender.com"
  status = 200

[[redirects]]
  from = "*"
  to = "https://backend-wbd-project.onrender.com"
  status = 200