[[redirects]]
  from = "/api/*"
  to = "https://backend-wbd-project.onrender.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/user/*"
  to = "https://backend-wbd-project.onrender.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/admin/*"
  to = "https://backend-wbd-project.onrender.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/auth/*"
  to = "https://backend-wbd-project.onrender.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}