version: "3.8"
services:
  
  backend-api:
    build: ./Backend
    ports:
      - "5000:5000"
    volumes:
      - logs:/app/logs
      - ./Backend/images:/app/images
      - ./Backend:/app
      - /app/node_modules
      

  reactfrontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend-api

volumes:
  data:
  logs: